name: Front - PRODUCTION - Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: mskelton/setup-yarn@main
        with:
          node-version: "16.14.2"
          cache: yarn

      - name: YARN Build
        env:
          ENV: production
        run: yarn build

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: ./.github/workflows/client_prod.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: Copy New Frontend Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/intechcrm/frontend/uat/intech-web/"
          rm: true

      - name: Build and Deploy Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "/home/intechcrm/frontend/uat/init.sh"
