name: Front - PRODUCTION - Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: mskelton/setup-yarn@main
        with:
          node-version: "16.14.2"
          cache: yarn

        - shell: bash
        run: mv ./.env.staging.local ./.env.production.local

      - name: YARN Build
        env:
          ENV: production
        run: yarn build

      - name: Copy New Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/Intech-Chat/intech-web/"
          rm: true

      - name: Build and Deploy Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "/home/Intech-Chat/init.sh"
